# Data Analysis - Mini project 01

## Tasks performed:

### 1. Define Single and Multi Dimensional Numpy arrays
### 2. Leverage Numpy built-in methods and functions such as .random, .arange, .eye, .zeros, and .ones
### 3. Perform mathematical operations in Numpy
### 4. Perform arrays slicing and indexing
### 5. Perform elements selection (conditional)
### 6. Understand Pandas fundamentals
### 7. Pandas with CSV and HTML data
### 8. Pandas operations
### 9. Pandas with functions
### 10. Perform sorting and ordering in pandas
### 11. Perform concatenating and merging with pandas
### 12. Concluding the mini project 01

In [4]:
# Task 01:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array
#list_1 contains the list of numbers
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1


[50, 60, 80, 100, 200, 300, 500, 600]

In [6]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
print(my_numpy_array)
type(my_numpy_array)

[ 50  60  80 100 200 300 500 600]


numpy.ndarray

In [7]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2,5,8], [7,3,6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

In [8]:
my_array = np.array([[3,7,9,3], [4,3,2,2]])
my_array

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [9]:
#Task 02:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.30334512, 0.20414065, 0.91424771, 0.73168945, 0.21541227,
       0.40751903, 0.59192126, 0.7399601 , 0.68827409, 0.30817848,
       0.78816638, 0.35706458, 0.05934813, 0.52575351, 0.14276038,
       0.77553606, 0.44708215, 0.7242053 , 0.51768992, 0.62380103])

In [12]:
# you can create a matrix of random number as well
#random.rand() will always produces outcomes between 0 and 1
x = np.random.rand(3,3)
x

array([[0.16758315, 0.48603705, 0.24919954],
       [0.2968724 , 0.63952142, 0.92785793],
       [0.37924692, 0.22228995, 0.87396855]])

In [13]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

39

In [20]:
lis = []
for i in range(0, 20):
    i = np.random.randint(1,50)
    lis.append(i)
y = np.array(lis)
print(y)
print(lis)
lis.sort()
print(lis)
uni = []
rep = []
for i in lis:
    if i not in uni:
        uni.append(i)
    else:
        rep.append(i)
print('Repeated numbers are: ', rep)
print('occurance = ', uni)

[40 34 30 18 30 24 29 11  3  6 35 36 35 26 33 12 39 48 47 39]
[40, 34, 30, 18, 30, 24, 29, 11, 3, 6, 35, 36, 35, 26, 33, 12, 39, 48, 47, 39]
[3, 6, 11, 12, 18, 24, 26, 29, 30, 30, 33, 34, 35, 35, 36, 39, 39, 40, 47, 48]
Repeated numbers are:  [30, 35, 39]
occurance =  [3, 6, 11, 12, 18, 24, 26, 29, 30, 33, 34, 35, 36, 39, 40, 47, 48]


In [21]:
x = np.random.randint(1,100,50)
x

array([38, 82, 95, 69, 99, 28, 19, 75, 46, 48, 41, 44, 52, 12, 66, 94, 94,
       47, 55, 18, 53, 67, 65, 58, 28, 43, 94, 32,  9, 57, 13, 65, 24, 45,
       93, 18, 46, 42, 64, 77, 32, 23, 89, 28, 89, 14, 23, 67, 11, 78])

In [22]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
print(x)
y = np.eye(3)
print(y)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Matrix of ones
x = np.ones((7,7))
print(x)
y= np.ones((2,3))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
#array of zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
z = np.ones((5,5))

In [29]:
y=x+z
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
num = int(input('Enter a positive integer: '))

if num < 0:
    print("Invalid input!")
if num >= 0:
    s = np.random.randint(1, num, 10)
    print(s)

Enter a positive integer: 6
[5 5 1 2 2 3 1 5 1 5]


In [31]:
# task 03: 
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
sums = x+y
sums

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
s = np.sqrt(sums)
s

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069])

In [37]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [38]:
x_ = np.array([5,7,20])
y_ = np.array([9,15,4])
distance = (x_**2 + y_**2)**0.5
z = np.sqrt(x_**2+y_**2)
print(z)
print("the distance btw x_ and y_ is: ", distance)

[10.29563014 16.55294536 20.39607805]
the distance btw x_ and y_ is:  [10.29563014 16.55294536 20.39607805]


In [39]:
# task 4:
import numpy as np
my_numpy_array = np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [40]:
# Access specific index from the numpy array
my_numpy_array[0]

3

In [41]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:]

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [42]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[:3] = 7
my_numpy_array

array([ 7,  7,  7,  2,  8, 10, 20, 50])

In [43]:
# Let's define a two dimensional numpy array
matriz = np.random.randint(1, 10, (4,4))
matriz

array([[7, 9, 7, 7],
       [9, 3, 4, 4],
       [6, 4, 5, 2],
       [6, 9, 4, 1]])

In [44]:
# Get a row from a mtrix
matriz[0] = 8
matriz

array([[8, 8, 8, 8],
       [9, 3, 4, 4],
       [6, 4, 5, 2],
       [6, 9, 4, 1]])

In [45]:
matriz[3] = 1
matriz

array([[8, 8, 8, 8],
       [9, 3, 4, 4],
       [6, 4, 5, 2],
       [1, 1, 1, 1]])

In [46]:
X = np.array([[2,30,20,-2,-4], [3,4,40,-3,-2], [-3,4,-6,90,10], [25,45,34,22,12],[13,24,22,32,37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [47]:
X[-1] = 0

In [48]:
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [49]:
# TASK 05:
MATRIX = np.random.randint(1,10,(5,5))
MATRIX

array([[8, 3, 7, 3, 3],
       [8, 3, 3, 5, 7],
       [1, 3, 7, 1, 6],
       [3, 1, 1, 9, 8],
       [5, 7, 3, 4, 9]])

In [50]:
new_matrix = MATRIX[ MATRIX%2 == 0]
new_matrix

array([8, 8, 6, 8, 4])

In [51]:
# Obtain odd elements only
odd_matrix = MATRIX[ MATRIX%2 != 0]
odd_matrix

array([3, 7, 3, 3, 3, 3, 5, 7, 1, 3, 7, 1, 3, 1, 1, 9, 5, 7, 3, 9])

In [53]:
X = np.array([[2,30,20,-2,-4], [3,4,40,-3,-2], [-3,4,-6,90,10], [25,45,34,22,12], [13,24,22,32,37]])
X[X<0] = 0
X[X%2 != 0] = -2
print(X)

[[ 2 30 20  0  0]
 [-2  4 40  0  0]
 [ 0  4  0 90 10]
 [-2 -2 34 22 12]
 [-2 24 22 32 -2]]


In [54]:
# task 6
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

import pandas as pd

In [55]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID': [111,222,333,444], 
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                            'Net Worth [$]': [3500, 29000, 10000, 2000],
                              'Years with bank':[3,4,9,5]})

In [56]:
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [57]:
portfolio_df = pd.DataFrame({'stocks': ['apple', 'ms', 'verizon'],
                            'number of shares': [5000, 2000, 20000],
                            'price per share': [500, 1000, 50]})
portfolio_df
portfolio_df['total value'] = portfolio_df['number of shares'] * portfolio_df['price per share']
portfolio_df_total_value = portfolio_df['total value'].sum()
portfolio_df_total_value

5500000

In [58]:
# task 7

!pip install lxml

In [59]:
!python -m pip install --upgrade pip

In [60]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [61]:
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [62]:
# Read tabular data using read_html
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [63]:
us_retirement_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
us_retirement_data[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

In [64]:
# task 8
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [111,222,333,444], 
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                            'Net Worth [$]': [3500, 29000, 10000, 2000],
                              'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [65]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [66]:
del bank_client_df['Bank Client Name']
bank_client_df

Bank Client ID  Net Worth [$]  Years with bank
0             111           3500                3
1             222          29000                4
2             333          10000                9
3             444           2000                5

In [67]:
new_pd = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]
new_pd

Bank Client ID  Net Worth [$]  Years with bank
1             222          29000                4
2             333          10000                9

In [68]:
combined_nw = new_pd['Net Worth [$]'].sum()
combined_nw

39000

In [69]:
#task 9:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [70]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [71]:
# You can apply a function to the DataFrame 
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [72]:
portfolio_df = pd.DataFrame({'stocks': ['apple', 'ms', 'verizon'],
                            'number of shares': [5000, 2000, 20000],
                            'price per share': [500, 1000, 50]})
portfolio_df

stocks  number of shares  price per share
0    apple              5000              500
1       ms              2000             1000
2  verizon             20000               50

In [73]:
def stock_prices(price):
    return (price * 3)+200
bank_client_df['Net worth [$]'].apply(stock_prices).sum()
#bank_client_df['Net worth [$]'].sum()

134300

In [74]:
#task 10:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [75]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by='Years with bank', inplace=True)

In [76]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [77]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},index = [0,1,2,3])

In [78]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [79]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                   'B': ['B4', 'B5', 'B6', 'B7'],
                   'C': ['C4', 'C5', 'C6', 'C7'],
                   'D': ['D4', 'D5', 'D6', 'D7']},index = [4,5,6,7])

In [80]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [81]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                   'B': ['B8', 'B9', 'B10', 'B11'],
                   'C': ['C8', 'C9', 'C10', 'C11'],
                   'D': ['D8', 'D9', 'D10', 'D11']},index = [8,9,10,11])

In [82]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [83]:
df4 = pd.concat([df1, df2, df3])
df4

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [84]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [85]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [86]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000